# Generated by Django 4.2.16 on 2024-10-09 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_item_code', models.CharField(max_length=20, unique=True)),
                ('vchr_item_name', models.CharField(max_length=100)),
                ('txt_description', models.TextField(blank=True, null=True)),
                ('dbl_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('int_quantity', models.IntegerField(default=0)),
                ('dat_created', models.DateTimeField(auto_now_add=True)),
                ('dat_updated', models.DateTimeField(null=True)),
                ('bln_active', models.BooleanField(default=True)),
                ('fk_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Masters',
                'db_table': 'item_master',
            },
        ),
    ]
